In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [13]:
arr = np.zeros((5,5))

In [14]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(0,10,2)

array([ 0., 10.])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.random.rand(5)

array([0.63871256, 0.15946882, 0.82620589, 0.87591664, 0.67712083])

In [21]:
np.random.rand(5) * 100

array([59.7115187 , 58.57690466, 39.70414803, 53.40451664, 84.64745148])

In [23]:
np.random.rand(5,4)

array([[0.81564372, 0.21912002, 0.3224827 , 0.58421674],
       [0.01890182, 0.07074032, 0.02026239, 0.79661636],
       [0.2167548 , 0.79958016, 0.83251735, 0.00538076],
       [0.42669503, 0.75092789, 0.32064495, 0.37068576],
       [0.29218412, 0.28246124, 0.19640144, 0.04091489]])

In [24]:
np.random.rand(5,4,3)

array([[[0.11182261, 0.8472614 , 0.24848203],
        [0.45384319, 0.8956951 , 0.16608703],
        [0.70071344, 0.90279985, 0.91344481],
        [0.66481571, 0.51965801, 0.66785931]],

       [[0.48129163, 0.43999927, 0.87546153],
        [0.00779801, 0.7532732 , 0.35201791],
        [0.23932908, 0.09483106, 0.9469403 ],
        [0.98722046, 0.82873267, 0.65085   ]],

       [[0.85473732, 0.29014209, 0.82727899],
        [0.33084913, 0.21407379, 0.15295616],
        [0.67984959, 0.59427617, 0.41996683],
        [0.18892716, 0.70428562, 0.25975844]],

       [[0.11186708, 0.23016112, 0.2606366 ],
        [0.3710893 , 0.75665762, 0.89102453],
        [0.93802625, 0.08790772, 0.0580991 ],
        [0.10173722, 0.06484248, 0.86332279]],

       [[0.87131616, 0.8633459 , 0.48529522],
        [0.0429177 , 0.04570892, 0.17185073],
        [0.95413491, 0.35958551, 0.81960157],
        [0.02332126, 0.13126498, 0.22185125]]])

In [25]:
np.random.randn(4)

array([ 0.87720528, -1.37982904, -0.03560089,  0.41778668])

In [26]:
np.random.randint(0, 100, 10)

array([24, 31, 24, 67, 99, 20, 78, 83, 32,  2])

In [27]:
arr = np.random.rand(25)

In [28]:
arr

array([0.45182957, 0.89079493, 0.61704929, 0.08248297, 0.73922622,
       0.81910464, 0.16893222, 0.95849627, 0.94976783, 0.34170001,
       0.99046139, 0.24681005, 0.56168302, 0.5151858 , 0.94982664,
       0.26256461, 0.00810839, 0.5016665 , 0.76631582, 0.21454588,
       0.58479011, 0.44451299, 0.13358925, 0.51383175, 0.86885316])

In [29]:
arr.reshape((5,5))

array([[0.45182957, 0.89079493, 0.61704929, 0.08248297, 0.73922622],
       [0.81910464, 0.16893222, 0.95849627, 0.94976783, 0.34170001],
       [0.99046139, 0.24681005, 0.56168302, 0.5151858 , 0.94982664],
       [0.26256461, 0.00810839, 0.5016665 , 0.76631582, 0.21454588],
       [0.58479011, 0.44451299, 0.13358925, 0.51383175, 0.86885316]])

In [30]:
arr

array([0.45182957, 0.89079493, 0.61704929, 0.08248297, 0.73922622,
       0.81910464, 0.16893222, 0.95849627, 0.94976783, 0.34170001,
       0.99046139, 0.24681005, 0.56168302, 0.5151858 , 0.94982664,
       0.26256461, 0.00810839, 0.5016665 , 0.76631582, 0.21454588,
       0.58479011, 0.44451299, 0.13358925, 0.51383175, 0.86885316])

In [31]:
arr.shape

(25,)

In [32]:
arr.max()

0.9904613917292957

In [33]:
arr.min()

0.008108386038171989

In [34]:
arr.argmax()

10

In [35]:
arr = arr.reshape((5,5))

In [36]:
arr.shape

(5, 5)

In [37]:
arr.argmax()

10

In [39]:
arr.argmin()

16